### ISSUE TITLE
helm template fails with "no cached repo found" due to missing index in temporary --repository-cache

### ISSUE THREAD

**Issue by TuomasAutio** [allenporter/flux-local#859]
I'm encountering an issue that seems closely related to the problems described in #857 and #666, where flux-local fails during the helm template execution step.

When defining the help repository cache, helm template command expects the helm index file to be located there and since it is not there it will fail to a error like.
```
Command 'helm template mend-renovate-ce renovate-renovate-helm/mend-renovate-ce --namespace renovate --repository-cache <HELM_CACHE_DIR> --repository-config <_tmp_dir>/repository-config.yaml --registry-config /dev/null --skip-crds --skip-tests --version 9.7.0 --values <_tmp_dir>/renovate-mend-renovate-ce-values.yaml' failed with return code 1
Error: no cached repo found. (try 'helm repo update'): open <HELM_CACHE_DIR>/<helmreponame>-index.yaml: no such file or directory
```

Seems like its running the helm repo update command with the default value `DEFAULT_REGISTRY_CONFIG = "/dev/null"` even though its defined in the CLI arguments

`DEBUG    flux_local.command:command.py:77 Running command: helm repo update --registry-config /dev/null --repository-cache <helm_cache_dir> --repository-config <_tmp_dir>/repository-config.yaml`

**Comment by allenporter** [comment]
This looks like the hell concurrency issue, but I can't tell for sure. Maybe we need a flag to limit help concurrency.  Perhaps check the version of help you are running to make sure it's not an older one that has been fixed (or maybe a newer one regressed).


I'm not quite understanding the comment about default values even though it's defined, since it all looks consistent between the two runs to me.

**Comment by TuomasAutio** [comment]
Tried with few different versions 3.17.2 and 3.16.0 but still the same :/

**Comment by allenporter** [comment]
Thanks, I may be misunderstanding the issue. Can you tell me more by what you mean by

> Seems like its running the helm repo update command with the default value DEFAULT_REGISTRY_CONFIG = "/dev/null" even though its defined in the CLI arguments

You're saying you pass `--registry-config` and its not being honored? Perhaps you can give me the full command you're running.

**Comment by TuomasAutio** [comment]
I'll try and see if I can come up with an example that can be replicated.
